# Scientific Programming in Python - Dictionaries and Functions

### Problem 1. Library, with dictionaries

We’ll revisit the Problem 3 of Assignment 2, where we had to manipulate some data from a fake
library.

In this problem, we had the following format for the data:


In [ ]:
[[123456,312314,531337],                     # Student IDS
 ['John Doe',' Jane Miller','Ted Johnson'],  # Student Names
 [1.49,0.00,8.12]]                           # Amounts owed

[[123456, 312314, 531337],
 ['John Doe', ' Jane Miller', 'Ted Johnson'],
 [1.49, 0.0, 8.12]]

>**(a)** Construct a dictionary to store this data, using the student ID (the ﬁrst big number) as the **key**, and the amount owed as the **values**.

> Use the code below to get you started. You can type the key, value pairs into the curly brackets `{ }`.

In [ ]:
import urllib.request

url = "http://ucl-cs-grad.github.io/scipython/notebooks/day2/library_data.txt"

urllib.request.urlretrieve(url, "library_data.txt")

print("파일 다운로드 완료!")

파일 다운로드 완료!


In [ ]:
student_id_to_amount_owed = {}

with open(r"library_data.txt", "r", encoding="utf-8") as f:
    for line in f:
        split = line.strip().split()

        # 데이터가 비어있는 줄 방지
        if not split:
            continue

        student_id = int(split[0])
        amount_owed = float(split[-1])

        student_id_to_amount_owed[student_id] = amount_owed

print(student_id_to_amount_owed)

{123456: 1.49, 312314: 0.0, 531337: 8.12, 273263: 0.0, 102931: 1.2, 391273: 10.39}


> **(b)** Use this dictionary to find out how much money the student with id `531337` owes.

> You should use square brackets `[ ]` to index into your dictionary.


In [ ]:
amount_owed = student_id_to_amount_owed[531337]
print("The student with id 531337 owes: ", amount_owed)

the student with id 531337 owes:  8.12


> Try also finding out how much 123456 owes. What about newly enrolled student 999888?

In [ ]:
amount_owed_by_123456 = student_id_to_amount_owed[123456]
print("The student with id 123456 owes: ", amount_owed_by_123456)

if 999888 in student_id_to_amount_owed:
    print(student_id_to_amount_owed[999888])
else:
    print("신입생(999888)의 연체 기록이 없다.")

The student with id 123456 owes:  1.49
신입생(999888)의 연체 기록이 없다.


> **(c)** Create another dictionary which maps the name of the student to its student id.  This time, instead of typing the values in by hand, fill in this dictionary by looping over the list `student_names_and_ids` given below:


In [ ]:
student_names_and_ids = [('John Doe', 123456), ('Jane Miller', 312314), ('Ted Johnson', 531337)]

studentname_to_id = {}  # initialise empty dictionary

for name, student_id in student_names_and_ids:
    studentname_to_id[name] = student_id
print(studentname_to_id)

# desired output : {'Jane Miller': 312314, 'John Doe': 123456, 'Ted Johnson': 531337}

{'John Doe': 123456, 'Jane Miller': 312314, 'Ted Johnson': 531337}



> **(c)** Print how much money 'John Doe' owes the library, using both of your dictionaries.

>  *(Hint: First find out John Doe's student ID, then use this to find out how much he owes)*

In [ ]:
John_doe_id = studentname_to_id['John Doe']

John_doe_balance = student_id_to_amount_owed[John_doe_id]
print(John_doe_balance)

1.49


> **(d)** Create the list of the names of students owing more than £1.0 to the library.

> *(Hint: If it is easier, first make a list of all the student IDs which owe more than £1.0 Then adapt the code to create a list of names instead).*


In [ ]:
bad_students = [
    name for name, s_id in studentname_to_id.items()
    if student_id_to_amount_owed.get(s_id, 0) > 1.0
]

print(bad_students)

['John Doe', 'Ted Johnson']


###Problem 2. Counting words

>**(a)** In this problem we’ll use the text of Alice in Wonderland to construct dictionaries counting the
number of times particular words and pairs of words appear.

In [ ]:
import urllib.request

URL = "http://ucl-cs-grad.github.io/scipython/notebooks/day2/alice.txt"
urllib.request.urlretrieve(URL, "alice.txt")

print("Alice in Wonderland 다운로드 완료!")

Alice in Wonderland 다운로드 완료!


This will create a new file called "alice.txt"

>**(b)** We'll process alice.txt in loops like this:

In [ ]:
f = open("alice.txt", "r")

# your code here (1)
words = {}

for line in f.readlines():
    for word in line.strip().split():
        # your code here (2)
        if word not in words:
            words[word] = 1
        else:
            words[word] += 1

# your code here (3)
print(words)

f.close()

{'Project': 78, "Gutenberg's": 2, "Alice's": 11, 'Adventures': 4, 'in': 401, 'Wonderland,': 3, 'by': 72, 'Lewis': 4, 'Carroll': 4, 'This': 20, 'eBook': 5, 'is': 89, 'for': 146, 'the': 1664, 'use': 24, 'of': 596, 'anyone': 4, 'anywhere': 3, 'at': 211, 'no': 72, 'cost': 3, 'and': 780, 'with': 214, 'almost': 8, 'restrictions': 2, 'whatsoever.': 2, 'You': 18, 'may': 26, 'copy': 8, 'it,': 41, 'give': 12, 'it': 356, 'away': 17, 'or': 137, 're-use': 2, 'under': 21, 'terms': 20, 'Gutenberg': 19, 'License': 8, 'included': 2, 'this': 122, 'online': 4, 'www.gutenberg.org': 2, 'Title:': 1, 'Wonderland': 2, 'Author:': 1, 'Posting': 1, 'Date:': 2, 'June': 1, '25,': 1, '2008': 1, '[EBook': 1, '#11]': 1, 'Release': 1, 'March,': 2, '1994': 1, '[Last': 1, 'updated:': 1, 'December': 1, '20,': 1, '2011]': 1, 'Language:': 1, 'English': 2, 'Character': 1, 'set': 23, 'encoding:': 1, 'ASCII': 1, '***': 6, 'START': 1, 'OF': 13, 'THIS': 8, 'PROJECT': 4, 'GUTENBERG': 3, 'EBOOK': 2, "ALICE'S": 5, 'ADVENTURES': 3,

>Modify this code so that it creates a new dictionary called words at (1).<br> For (2), if a word
is not already in the dictionary words, then add it to the dictionary with a value of 1. <br>If a
word is already in the dictionary words, then increment the value stored in the dictionary
by one.<br>

>At location (3), print out the dictionary words.

>**(b)** How many times does the word “the” appear? What about the word “The”?

In [ ]:
print("Word 'the':", words.get("the", 0))
print("Word 'The':", words.get("The", 0))

Word 'the': 1664
Word 'The': 100


>**(d)** Modify the code so words are counted independent of whether they are made of upper or
lower case letters. i.e., “the”, “The” and “tHE” are all treated as the same word.


In [ ]:
f = open("alice.txt", "r")

words = {}

for line in f.readlines():
    for word in line.strip().split():
        clean_word = word.lower()

        if clean_word not in words:
            words[clean_word] = 1
        else:
            words[clean_word] += 1

f.close()

print(f"'the' 등장 횟수 (대소문자 무관): {words.get('the', 0)}")

'the' 등장 횟수 (대소문자 무관): 1777


>**(e)** Repeat the previous exercise, but instead of counting the number of times a word appears,
count the number of times pairs of words appear. You might ﬁnd it useful to store the
previous word in a variable.

In [ ]:
f = open("alice.txt", "r")

word_pairs = {}
previous_word = None

for line in f.readlines():
    for word in line.strip().split():
        clean_word = word.lower()

        # 첫 번째 단어가 아니라 이전 단어가 존재하는 경우에만 쌍을 생성
        if previous_word is not None:
            pair = (previous_word, clean_word)

            if pair not in word_pairs:
                word_pairs[pair] = 1
            else:
                word_pairs[pair] += 1

        # 현재 단어를 다음 반복을 위한 previous_word로 업데이트
        previous_word = clean_word

f.close()

>**(f)** What are the most common words and pairs of words in Alice in Wonderland?<br> You might find the *sorted* function or the *sort* function for lists to be useful.


In [ ]:
sorted_pairs = sorted(word_pairs.items(), key=lambda x: x[1], reverse=True)
print("가장 자주 등장하는 단어 쌍 Top 5:")
for pair, count in sorted_pairs[:5]:
    print(f"{pair}: {count}회")

가장 자주 등장하는 단어 쌍 Top 5:
('said', 'the'): 207회
('of', 'the'): 154회
('in', 'a'): 101회
('in', 'the'): 92회
('to', 'the'): 84회


### Problem 4. ArgMax and ArgSort

>**(a)** Finding the index of the largest (or smallest) element in a list is a commonly needed opera-
tion, but Python does not provide this function in its standard library (numpy will provide those). Write two functions


In [ ]:
def argmax(list_input):
    if not list_input:
        return None

    max_idx = 0
    max_val = list_input[0]

    for idx, val in enumerate(list_input):
        if val > max_val:
            max_val = val
            max_idx = idx

    return max_idx


def argmin(list_input):
    if not list_input:
        return None

    min_idx = 0
    min_val = list_input[0]

    for idx, val in enumerate(list_input):
        if val < min_val:
            min_val = val
            min_idx = idx

    return min_idx

>that return the index of the largest and smallest element in the list *list_input* respectively. Example output:


    >>> list1 = [1,3,2,6,0,2,3,4,5]
    >>> argmax(list1)
    3
    >>> argmin(list1)
    4

In [ ]:
# try it here
list1 = [1,3,2,6,0,2,3,4,5]
print(argmax(list1))
print(argmin(list1))

3
4


>**(b)** **(extra)** Instead of just finding the index of the largest or smallest element, one might be interested in the entire list of indices that would sort the list. In one of the previous exercises we presented you with this piece of code for finding the indices that sort a list.


In [ ]:
l = [1,3,2,6,0,2,3,4,5]
zip(*sorted(zip(l, range(len(l)))))[1]

>It works by combining the list with the list of indices, sorting the combined list, and then untangling the results. Have a look at the documentation of the *zip* function to understand how it works. Write a function:

In [ ]:
def argsort(l):
    return sorted(range(len(l)), key=lambda i: l[i])

>that returns the list of indices that would sort the list, but instead of using the hard to read
line above that uses zip, use list comprehensions. Example output:

    >>> l = [1,3,2,6,0,2,3,4,5]
    >>> argsort(l)
    [4, 0, 2, 5, 1, 6, 7, 8, 3]
    >>> [l[i] for i in argsort(l)]
    [0, 1, 2, 2, 3, 3, 4, 5, 6]


In [ ]:
# try it here
l = [1,3,2,6,0,2,3,4,5]
print(argsort(l))
print([l[i] for i in argsort(l)])

[4, 0, 2, 5, 1, 6, 7, 8, 3]
[0, 1, 2, 2, 3, 3, 4, 5, 6]


### Problem 5. Simple ciphers


Suppose you wish to send your friend a message, and if someone happens to look at it, you do not want them to know what it says.<br>
A simple way of doing this is to replace each letter, with
a different one.<br>
For example, suppose I wish to send the phrase “dancing is silent poetry”.<br>
By exchanging each letter with another, we can encode this as: “robqwbu wg gwzsbh dcshfm”.

>**(a)** Write a function that swaps the letter in a string according to a dictionary. For example:


In [ ]:
def swapdict(string, dic):
    result = ""
    for char in string:
        if char in dic:
            result += dic[char]
        else:
            result += char
    return result

    >>> print swapdict('hello', {'e': 'i'})
    hillo
    >>> print swapdict('hello', {'l': 'w'})
    hewwo
    >>> print swapdict('hello', {'l': 'm', 'h': 'p', 'e': 'o', 'o': 'e'})
    pomme

In [ ]:
# your code here
print(swapdict('hello', {'e': 'i'}))

hillo


>**(b)** Write a function that generates a dictionary whose keys are letters of the alphabet, and whose values are those letters shifted along by a given number of letters.


In [ ]:
import string

def shiftdict(i):
    alphabet = string.ascii_lowercase
    return {char: alphabet[(idx + i) % 26] for idx, char in enumerate(alphabet)}

    >>> print shiftdict(0)
    {'a': 'a', 'b': 'b', ..., 'z': 'z'}
    >>> print shiftdict(3)
    {'a': 'd', 'b': 'e', ..., 'z': 'c'}
    >>> print shiftdict(13)
    {'a': 'n', 'b': 'o', ..., 'z': 'm'}

>In the first case, the letters are not shifted, because the argument to *shiftdict* is zero. In the second case, letters are shifted along by three letters: “a” is the first letter, and “d” is the forth letter, and so key “a” points to letter “d”.

In [ ]:
# try it here
print(shiftdict(3))

{'a': 'd', 'b': 'e', 'c': 'f', 'd': 'g', 'e': 'h', 'f': 'i', 'g': 'j', 'h': 'k', 'i': 'l', 'j': 'm', 'k': 'n', 'l': 'o', 'm': 'p', 'n': 'q', 'o': 'r', 'p': 's', 'q': 't', 'r': 'u', 's': 'v', 't': 'w', 'u': 'x', 'v': 'y', 'w': 'z', 'x': 'a', 'y': 'b', 'z': 'c'}


>**(c)** Now we are ready to encode our message: “dancing is silent poetry”.


    >>> print swapdict('dancing is silent poetry', shiftdict(14))

In [ ]:
print(swapdict('dancing is silent poetry', shiftdict(14)))

robqwbu wg gwzsbh dcshfm


>Check that it matches the encoding given above.


>**(d)** Write a function that takes a dictionary and swaps the roles of the keys and the values.


In [ ]:
def invertdict(dictionary):
    return {value: key for key, value in dictionary.items()}

Here are some examples to check it works:

    >>> invertdict({'a':'b'})
    {'b': 'a'}
    >>> invertdict({'b':'a', 'a': 'b'})
    {'a': 'b', 'b': 'a'}
    >>> invertdict({'a':'b', 'b': 'c', 'c': 'a'})
    {'a': 'c', 'b': 'a','c': 'b'}

In [ ]:
invertdict({'a':'b', 'b': 'c', 'c': 'a'})

{'b': 'a', 'c': 'b', 'a': 'c'}

>**(e)** Can you decode this message, that was encoded using the same scheme? “qzuipo nblft ju tjnqmf ipqfgvmmz”. Use only *invertdict*, *swapdict* and *shiftdict*.


In [ ]:
decode_dict = invertdict(shiftdict(1))
secret_message = "qzuipo nblft ju tjnqmf ipqfgvmmz"
decoded_message = swapdict(secret_message, decode_dict)

print(decoded_message)

python makes it simple hopefully


>**(f)** You notice that your friend is sending encrypted messages to other people, but they appear to be encoded using a different argument to shiftdict.<br>
Use a for-loop, swapdict and shiftdict to work out the encoding scheme, and what this message says: “nyhcpaf pz aol yvva vm spnoaulzz”.


In [ ]:
secret_message = "nyhcpaf pz aol yvva vm spnoaulzz"

for shift in range(1, 26):
    # shift 크기만큼 복호화하기 위해 사전 반전
    decode_dict = invertdict(shiftdict(shift))
    decoded_text = swapdict(secret_message, decode_dict)

    print(f"Shift {shift:2d}: {decoded_text}")

Shift  1: mxgboze oy znk xuuz ul romnztkyy
Shift  2: lwfanyd nx ymj wtty tk qnlmysjxx
Shift  3: kvezmxc mw xli vssx sj pmklxriww
Shift  4: judylwb lv wkh urrw ri oljkwqhvv
Shift  5: itcxkva ku vjg tqqv qh nkijvpguu
Shift  6: hsbwjuz jt uif sppu pg mjhiuoftt
Shift  7: gravity is the root of lightness
Shift  8: fqzuhsx hr sgd qnns ne khfgsmdrr
Shift  9: epytgrw gq rfc pmmr md jgefrlcqq
Shift 10: doxsfqv fp qeb ollq lc ifdeqkbpp
Shift 11: cnwrepu eo pda nkkp kb hecdpjaoo
Shift 12: bmvqdot dn ocz mjjo ja gdbcoiznn
Shift 13: alupcns cm nby liin iz fcabnhymm
Shift 14: zktobmr bl max khhm hy ebzamgxll
Shift 15: yjsnalq ak lzw jggl gx dayzlfwkk
Shift 16: xirmzkp zj kyv iffk fw czxykevjj
Shift 17: whqlyjo yi jxu heej ev bywxjduii
Shift 18: vgpkxin xh iwt gddi du axvwicthh
Shift 19: ufojwhm wg hvs fcch ct zwuvhbsgg
Shift 20: tenivgl vf gur ebbg bs yvtugarff
Shift 21: sdmhufk ue ftq daaf ar xustfzqee
Shift 22: rclgtej td esp czze zq wtrseypdd
Shift 23: qbkfsdi sc dro byyd yp vsqrdxocc
Shift 24: p